### PR TITLE
Allow for SSL connection options to be passed to AnyEvent::Handle

### PR DESCRIPTION
**Pull request by atoomic**
Add an extra option to pass directly a has of AnyEvent::TLS options

### CODE REVIEW

**Comment by cPanelScott** [comment]
This PR works and allows connections to SSL-speaking RabbitMQ servers. It doesn't allow for peer verification, but I can propose that in a separate PR.

This PR is old, but it is certainly valuable to anyone who uses RabbitMQ with SSL.

@bobtfish Would you be willing to merge the PR as is, and accept a separate PR to improve peer validation?

**Comment by davel** [comment]
Hi @cPanelScott,

Have you been in touch with @bobtfish about this change outside of this PR? I'm not currently using AnyEvent::RabbitMQ, but could release the change. It looks fairly safe to me.

**Comment by cPanelScott** [comment]
I haven't been in touch with @bobtfish. I have one other change to propose. Would you be willing to merge this, and then consider a second PR before releasing?

**Comment by davel** [comment]
Hello @cPanelScott. I have merged your change and made a dev release. https://metacpan.org/release/DLAMBLEY/AnyEvent-RabbitMQ-1.19_01

Can you confirm that it works? Adding host verification to TLS sounds very sensible to me, please go ahead.

All the best,
Dave

**Comment by cPanelScott** [comment]
Yes, this change works. It might take me a few weeks to get the next PR in. It's a one-line addition, but I need to work something else out first.

**Pull request merged**
